name: ModuOps
version: 5.6.0
build: 1
encrypt stacks: random
multiple instances: false
relaunch in background: false
creator code: com.bobhall.moduops
application data folder:
  user:
    default:
    macos:
    windows: ModuOps
    linux: ModuOps
    ios:
    android:
  shared:
    default:
    macos:
    windows: ModuOps
    linux: ModuOps
preferences filename:
  user:
    default: ModuOps.prefs
    macos: com.moduops.moduops
    windows:
    linux:
    ios:
    android:
  shared:
    default: ModuOps.prefs
    macos:
    windows:
    linux:
ui:
  - folder: ./ui
libraries:
  - folder: ./libraries
frontscripts:
  - folder: ./frontscripts
backscripts:
  - folder: ./backscripts
helpers:
  - folder: ./helpers
  - filename: '[[FRAMEWORK]]/helpers/preferences'
  - filename: '[[FRAMEWORK]]/helpers/file_system'
  - filename: '[[FRAMEWORK]]/helpers/logger'
behaviors:
  - folder: ./behaviors
build folder: ../builds
build profiles:
  all profiles:
    packager callbacks stackfile:
    certificates:
      macos:
        name: Robert Hall (723D68M8DS)
    copy files:
      all platforms:
        - filename: assets
      macos:
      windows:
      linux:
      ios:
      android:
      inno setup:
        - filename: ../app/helpers/inno_setup/ModuOps.iss
    dropDMG:
      filename: ModuOps

  release:
  beta:
file extensions:
  MOP2: mop2
dropDMG:
  format: bzip2
  layout name: moduops
  license name:
inno setup:
  file flags: ignoreversion
  folder flags: ignoreversion recursesubdirs createallsubdirs
  executable flags: ignoreversion
  windows compiler:
